server:
  port: 8080 # Render automatically detects this
  address: 0.0.0.0
lavalink:
  server:
    password: "youshallnotpass" # Aap ise change kar sakte hain
    sources:
      youtube: true
      bandcamp: true
      soundcloud: true
      twitch: true
      vimeo: true
      http: true
      local: false
    filters:
      volume: true
      equalizer: true
      timescale: true
      vibrato: true
      tremolo: true
      rotation: true
      distortion: true
    bufferDurationMs: 400
    frameBufferDurationMs: 5000
    opusEncodingQuality: 10
    resamplingQuality: LOW
    trackStuckThresholdMs: 10000
    useSeekGhosting: true
    youtubePlaylistLoadLimit: 6
    playerUpdateInterval: 5

metrics:
  prometheus:
    enabled: false
    endpoint: /metrics

logging:
  file:
    path: ./logs/

  level:
    root: INFO
    lavalink: INFO
