server:
  port: 8080 # Render automatically detects this
  address: 0.0.0.0
lavalink:
  plugins:
    # Latest 2026 version of the YouTube Source Plugin
    - dependency: "dev.lavalink.youtube:youtube-plugin:1.11.5"
      repository: "https://maven.lavalink.dev/releases"
  server:
    password: "youshallnotpass" # Aap ise change kar sakte hain
    sources:
      youtube: False
      bandcamp: true
      soundcloud: true
      twitch: true
      vimeo: true
      http: true
      local: false
    filters:
      volume: true
      equalizer: true
      timescale: true
      vibrato: true
      tremolo: true
      rotation: true
      distortion: true
    bufferDurationMs: 400
    frameBufferDurationMs: 5000
    opusEncodingQuality: 10
    resamplingQuality: LOW
    trackStuckThresholdMs: 10000
    useSeekGhosting: true
    youtubePlaylistLoadLimit: 6
    playerUpdateInterval: 5
plugins:
  youtube:
    enabled: true
    allowSearch: true
    allowDirectVideoIds: true
    allowDirectPlaylistIds: true
    # Public clients that work best without any login/auth
    clients:
      - TVHTML5_SIMPLY
      - ANDROID_VR
      - MUSIC
      - WEB
    # OAuth is explicitly turned off
    oauth:
      enabled: false    
metrics:
  prometheus:
    enabled: false
    endpoint: /metrics

logging:
  file:
    path: ./logs/

  level:
    root: INFO
    lavalink: INFO
